name: Beta Release

on:
  push:
    tags:
      - "beta-*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build and Release Beta
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Procursus
        uses: beerpiss/procursus-action@v2
        with:
          packages: ldid xz-utils cmark make
          cache: true
          cache-path: ~/__cache

      - name: Set up Theos
        run: git clone --recursive --depth=1 "https://github.com/theos/theos.git" ~/theos

      - name: Build package
        id: package_build
        run: |
          gmake package THEOS=~/theos
          echo "package=$(cat .theos/last_package)" >> "$GITHUB_OUTPUT"

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: NewTerm3-beta
          path: ${{ steps.package_build.outputs.package }}

      - name: Publish beta release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          generate_release_notes: true
          files: |
            ${{ steps.package_build.outputs.package }}
