name: Beta Release

on:
  push:
    tags:
      - "beta-*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build and Release Beta
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Procursus
        uses: beerpiss/procursus-action@v2
        with:
          packages: ldid xz-utils cmark make
          cache: true
          cache-path: ~/__cache

      - name: Set up Theos
        run: git clone --recursive --depth=1 "https://github.com/theos/theos.git" ~/theos

      - name: Configure build environment
        run: |
          echo "TARGET_CODESIGN_ALLOCATE=$(xcrun --find codesign_allocate)" >> "$GITHUB_ENV"

      - name: Build package
        id: package_build
        run: |
          make package THEOS=~/theos USE_PREBUILT_APP=0 TARGET_CODESIGN_ALLOCATE="$TARGET_CODESIGN_ALLOCATE"
          package_path="$(cat .theos/last_package)"
          cp "$package_path" ./packages/com.dav.n3wterm.deb
          echo "package=$package_path" >> "$GITHUB_OUTPUT"
          echo "release_package=./packages/com.dav.n3wterm.deb" >> "$GITHUB_OUTPUT"

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: com.dav.n3wterm-beta
          path: ${{ steps.package_build.outputs.release_package }}

      - name: Publish beta release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          generate_release_notes: true
          files: |
            ${{ steps.package_build.outputs.release_package }}
